"""Confirmation messages that quote user-supplied text.

`onclick="return confirm('Revoke {{ name }}')"` puts two parsers in sequence:
Jinja escapes for HTML, the HTML parser decodes those entities and hands the
result to the JavaScript parser — so an apostrophe in the name arrives as a real
quote, closes the string early, and whatever follows executes. HTML escaping is
the wrong escaping for a JavaScript context.

A data attribute has no such problem: the value is read as a DOM string and
passed to confirm(), never parsed as code.
"""
import re

import pytest

from app.models.api_token import ApiToken
from tests.conftest import CSRF, make_user, prime_csrf

BREAKOUT = "x'); fetch('/admin/users'); alert(1); //"


@pytest.fixture
def admin_client(client, db, login):
    make_user('admin', role='admin', password='Password123!')
    login('admin', 'Password123!')
    prime_csrf(client)
    return client


def user_page(client, db):
    from app.models.user import User
    admin = User.query.filter_by(username='admin').one()
    return admin.id, client.get(f'/admin/users/{admin.id}/edit').get_data(as_text=True)


def issue_token(client, user_id, name):
    return client.post(f'/admin/users/{user_id}/api-token',
                       data={'csrf_token': CSRF, 'token_name': name})


# ── the fix ────────────────────────────────────────────────────────────────

def test_the_revoke_button_no_longer_builds_javascript(admin_client, db):
    user_id, _ = user_page(admin_client, db)
    issue_token(admin_client, user_id, 'Home Assistant')
    _, html = user_page(admin_client, db)

    assert 'data-confirm=' in html
    # The name must not end up inside a JS string literal in an attribute.
    assert "confirm('Revoke" not in html
    assert not re.search(r'onclick="return confirm\([^"]*Home Assistant', html)


def test_a_name_that_would_break_out_is_inert(admin_client, db):
    """The payload is still displayed — it just cannot execute."""
    user_id, _ = user_page(admin_client, db)
    issue_token(admin_client, user_id, BREAKOUT)
    _, html = user_page(admin_client, db)

    attribute = re.search(r'data-confirm="([^"]*)"', html).group(1)
    # Quotes survive only as entities, so they never terminate the attribute...
    assert "'" not in attribute
    assert '&#39;' in attribute
    # ...and nothing in the page treats it as script.
    assert 'onclick="return confirm' not in html
    assert "fetch('/admin/users')" not in html


def test_the_name_is_still_shown_to_the_admin(admin_client, db):
    """Escaping must not swallow the text; an admin has to recognise the token
    they are about to revoke."""
    user_id, _ = user_page(admin_client, db)
    issue_token(admin_client, user_id, "Kevin's laptop")
    _, html = user_page(admin_client, db)
    assert 'Kevin&#39;s laptop' in html or "Kevin's laptop" in html


def test_the_token_is_actually_revocable(admin_client, db):
    """Moving the confirm into JS must not break the form itself."""
    user_id, _ = user_page(admin_client, db)
    issue_token(admin_client, user_id, 'Scratch')
    token = ApiToken.query.one()

    admin_client.post(f'/admin/users/{user_id}/api-token/{token.id}/revoke',
                      data={'csrf_token': CSRF})
    assert ApiToken.query.count() == 0


# ── the handler that replaces it ───────────────────────────────────────────

def test_the_javascript_reads_the_attribute_rather_than_being_generated():
    from pathlib import Path
    main_js = (Path(__file__).resolve().parent.parent
               / 'app' / 'static' / 'js' / 'main.js').read_text()
    assert "form[data-confirm]:not([data-async])" in main_js
    assert 'form.dataset.confirm' in main_js


def test_async_forms_are_excluded_so_they_do_not_ask_twice():
    """initAsyncActions runs its own confirm for data-async forms."""
    from pathlib import Path
    main_js = (Path(__file__).resolve().parent.parent
               / 'app' / 'static' / 'js' / 'main.js').read_text()
    assert ':not([data-async])' in main_js


def test_no_template_interpolates_data_into_an_inline_confirm():
    """The class of bug, not just this instance. Server-generated identifiers
    such as a work order number are fine; anything a user can type is not."""
    from pathlib import Path
    templates = (Path(__file__).resolve().parent.parent / 'app' / 'templates')
    offenders = []
    for path in templates.rglob('*.html'):
        for line in path.read_text().split('\n'):
            if 'onclick=' in line and 'confirm(' in line and '{{' in line:
                # wo_number is generated by the app (WO-YYYY-NNNNN), never typed.
                if 'wo_number' not in line:
                    offenders.append(f'{path.name}: {line.strip()[:90]}')
    assert not offenders, 'user-supplied text inside an inline confirm:\n' + '\n'.join(offenders)
