"""pm schedule based on last completed

Revision ID: 38d09596990e
Revises: d0f2e5512503
Create Date: 2026-08-30 19:00:21.026904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d09596990e'
down_revision = 'd0f2e5512503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_from_completion', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pms', schema=None) as batch_op:
        batch_op.drop_column('schedule_from_completion')

    # ### end Alembic commands ###
