"""asset and location hierarchy and lifecycle status

Adds self-referencing parent_id to assets and locations, plus a lifecycle
status. Existing rows get status='active' via the server default, so this is
safe to run against a populated database.

Revision ID: 38f9ece5fb24
Revises: bbb3095b3740
Create Date: 2026-08-30 12:31:12.028859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f9ece5fb24'
down_revision = 'bbb3095b3740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
        batch_op.create_index(batch_op.f('ix_assets_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key('fk_assets_parent_id_assets', 'assets', ['parent_id'], ['id'])

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
        batch_op.create_index(batch_op.f('ix_locations_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key('fk_locations_parent_id_locations', 'locations', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_locations_parent_id_locations', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_locations_parent_id'))
        batch_op.drop_column('status')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assets_parent_id_assets', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_assets_parent_id'))
        batch_op.drop_column('status')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
