"""pm lead time and overdue grace

Revision ID: 483511528c84
Revises: 38d09596990e
Create Date: 2026-08-30 21:05:08.157422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483511528c84'
down_revision = '38d09596990e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generate_lead_days', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('overdue_grace_days', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overdue_grace_days', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_column('overdue_grace_days')

    with op.batch_alter_table('pms', schema=None) as batch_op:
        batch_op.drop_column('overdue_grace_days')
        batch_op.drop_column('generate_lead_days')

    # ### end Alembic commands ###
