"""auth attempt log for lockouts

Revision ID: 497dbbca6894
Revises: 54945ed7d378
Create Date: 2026-09-02 20:01:11.717485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497dbbca6894'
down_revision = '54945ed7d378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=120), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_attempts_identifier'), ['identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_attempts_ip_address'), ['ip_address'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_attempts_ip_address'))
        batch_op.drop_index(batch_op.f('ix_auth_attempts_identifier'))
        batch_op.drop_index(batch_op.f('ix_auth_attempts_created_at'))

    op.drop_table('auth_attempts')
    # ### end Alembic commands ###
