"""work order materials and asset materials list

Revision ID: 54945ed7d378
Revises: bf04a0bb5a89
Create Date: 2026-09-01 21:36:02.260224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54945ed7d378'
down_revision = 'bf04a0bb5a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('part_number', sa.String(length=80), nullable=True),
    sa.Column('quantity', sa.String(length=60), nullable=True),
    sa.Column('times_used', sa.Integer(), server_default='1', nullable=False),
    sa.Column('first_used_on', sa.Date(), nullable=True),
    sa.Column('last_used_on', sa.Date(), nullable=True),
    sa.Column('last_work_order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_work_order_id'], ['work_orders.id'], name='fk_asset_materials_work_order', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_materials', schema=None) as batch_op:
        batch_op.create_index('ix_asset_materials_asset_id', ['asset_id'], unique=False)

    op.create_table('work_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.String(length=60), nullable=True),
    sa.Column('part_number', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_items_work_order_id'), ['work_order_id'], unique=False)

    with op.batch_alter_table('job_plan_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part_number', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_plan_items', schema=None) as batch_op:
        batch_op.drop_column('part_number')

    with op.batch_alter_table('work_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_items_work_order_id'))

    op.drop_table('work_order_items')
    with op.batch_alter_table('asset_materials', schema=None) as batch_op:
        batch_op.drop_index('ix_asset_materials_asset_id')

    op.drop_table('asset_materials')
    # ### end Alembic commands ###
