"""asset photo

Revision ID: 69ee6cfb2ed3
Revises: 713382d2c88b
Create Date: 2026-08-30 15:24:55.968063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ee6cfb2ed3'
down_revision = '713382d2c88b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_attachment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_assets_image_attachment', 'attachments', ['image_attachment_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assets_image_attachment', type_='foreignkey')
        batch_op.drop_column('image_attachment_id')

    # ### end Alembic commands ###
