"""work order status change stamp

Revision ID: 84b7eef551cb
Revises: 51c945f54775
Create Date: 2026-09-07 23:20:38.970711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b7eef551cb'
down_revision = '51c945f54775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_changed_at', sa.DateTime(), nullable=True))

    # Backfill so existing work orders are not treated as having changed status
    # just now — which, with auto-archiving on, would make every closed record
    # look freshly closed and delay it by the full window.
    #
    # completed_date is the best evidence where it exists. Otherwise updated_at,
    # which for a record nobody has touched since closing it is exactly right,
    # and for one that has been edited is still far closer than "now".
    op.execute("""
        UPDATE work_orders
           SET status_changed_at = COALESCE(
                   CASE WHEN completed_date IS NOT NULL
                        THEN datetime(completed_date) END,
                   updated_at,
                   created_at)
         WHERE status_changed_at IS NULL
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_column('status_changed_at')

    # ### end Alembic commands ###
