"""pm work order priority

Revision ID: 90f7064e9bf0
Revises: 483511528c84
Create Date: 2026-08-30 23:02:54.177628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f7064e9bf0'
down_revision = '483511528c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wo_priority', sa.String(length=20), server_default='medium', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pms', schema=None) as batch_op:
        batch_op.drop_column('wo_priority')

    # ### end Alembic commands ###
