"""api tokens

Revision ID: bcc497dee9ef
Revises: 1999d973e2f0
Create Date: 2026-08-31 20:39:26.370895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc497dee9ef'
down_revision = '1999d973e2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_token_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('api_token_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('api_token_last_used', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_api_token_hash'), ['api_token_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_api_token_hash'))
        batch_op.drop_column('api_token_last_used')
        batch_op.drop_column('api_token_created')
        batch_op.drop_column('api_token_hash')

    # ### end Alembic commands ###
