"""job plan materials and tools

Revision ID: d0f2e5512503
Revises: 69ee6cfb2ed3
Create Date: 2026-08-30 17:01:28.300574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f2e5512503'
down_revision = '69ee6cfb2ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_plan_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['job_plan_id'], ['job_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_plan_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_plan_items_job_plan_id'), ['job_plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_plan_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_plan_items_job_plan_id'))

    op.drop_table('job_plan_items')
    # ### end Alembic commands ###
